### ISSUE TITLE
First server run errors

### ISSUE THREAD

**Issue by gmodmania** [callmephil/SunWellCore#1]
Max allowed socket connections 1024
SQL(p): INSERT INTO pool_quest_save (pool_id, quest_id) VALUES (385, 13156)
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 6 queries not executed.

Bad mysql config or what? 

Thanks

**Comment by callmephil** [comment]
I get those errors sometime too, yes i guess bad MySQL Config. SunWell.pl has shared "Extras" with a config file for MySQL.
