### ISSUE TITLE
 Mulitplier for creature spell damage.

### ISSUE THREAD

**Issue by Motorheadx** [callmephil/SunWellCore#10]
Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 1
Rate.Creature.Elite.RARE.SpellDamage      = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1

Not work!

**Comment by callmephil** [comment]
Fixed With Extra Checks than Usual TrinityCore #Todo Test In All conditions.
