### ISSUE TITLE
Some NPC say text was missing in Dalaran.

### ISSUE THREAD

**Issue by tea91** [callmephil/SunWellCore#11]
Like this:

[NPC] Linda Ann Kastinglow & Arcanist Alec - Say text
https://github.com/TrinityCore/TrinityCore/issues/12524

In 10 yard and 5m cooltime, Vendor NPC need to say 'welcome or hello' to player on Dalaran.

and Some NPC text was missing, either. I'd check to NPC "great hexer ohodo" on Dalaran. He's creature_text was gone.
https://github.com/TrinityCore/TrinityCore/issues/5280

NPC: Dalaran Citizen and Great Hexer Ohodo
https://github.com/TrinityCore/TrinityCore/issues/13712

Please check if you have some time and Cheer. :+1: 

Thx.

**Comment by phoe1** [comment]
Great Work

**Comment by callmephil** [comment]
Thanks i Will Check them out. if those fix are working without having to edit could make a pull request ?
