### ISSUE TITLE
The Horde and the Alliance party not work healing and buff

### ISSUE THREAD

**Issue by Motorheadx** [callmephil/SunWellCore#14]

**Comment by callmephil** [comment]
Please Describe Better the issue.

**Comment by Motorheadx** [comment]
not heal hostile faction in the party

**Comment by callmephil** [comment]
it's related to #https://github.com/callmephil/SunWellCore/commit/54cb711edcde7db4f04a4e2a52b35ef4c0e276a4 ?

**Comment by Motorheadx** [comment]
Yes =))
