### ISSUE TITLE
will fix to custom patches?

### ISSUE THREAD

**Issue by Motorheadx** [callmephil/SunWellCore#19]
I'm not asking to add a patch , please add files which no results were compiled for them

**Comment by Motorheadx** [comment]
in no source files to work with patches

**Comment by Motorheadx** [comment]
and old version of the patch is also not compile , there's no files for them

**Comment by callmephil** [comment]
if you have weakness in scripting i would recommend you to use TrinityCore Sources for your custom patches. & use SunWellCore To Fix the issues you get on TrinityCore.
