### ISSUE TITLE
spell mage 31661 and 44457 fix please =)

### ISSUE THREAD

**Issue by Motorheadx** [callmephil/SunWellCore#26]
Wait for the explosion and the magic of the dragon's Breath will be removed , and the dragon's breath should not be removed

**Comment by ghost** [comment]
http://www.wowhead.com/spell=31661/dragons-breath
Any direct damage will cancel the effect.

**Comment by Motorheadx** [comment]
he is a living bomb should not be deleted notes patch 3.3.5 =)

**Comment by lashia** [comment]
Disorient effects will break on any direct damage. Casting another damage spell will break the effect.

**Comment by Motorheadx** [comment]
https://github.com/TrinityCore/TrinityCore/issues/8891

**Comment by callmephil** [comment]
he's right living bomb should not break dragon breath effect. however i tested in-game and it works well. you're not using correct core/database @Motorheadx

**Comment by Motorheadx** [comment]
I don't know the base downloaded from sunwell.pl

**Comment by callmephil** [comment]
Living Bombs + Dragon's Breath Should Works like this :
application of living bomb breaks dragon's breath.
tick-doesn't break
explosion-doesn't break

**Comment by callmephil** [comment]
Then @Motorheadx you have to re-test and verify you're using the correct core. because it's perfectly working for me.

**Comment by Motorheadx** [comment]
well thanks for the reply will check as you said
