### ISSUE TITLE
Error compile Linux Debian

### ISSUE THREAD

**Issue by Motorheadx** [callmephil/SunWellCore#29]
cmake ../ -DPREFIX=/home/macabra/release/macabracore -DTOOLS=1 -DCMAKE_CXX_FLAGS=»${CMAKE_C_FLAGS}» -DDO_RA=1 -DLARGE_CELL=1 -DACE_LIBRARY=/home/.sys/lib/libACE.so -DACE_INCLUDE_DIR=/home/.sys/include/ -DSSLLIB=/home/.sys/lib/libssl.so
with such parameters error

/usr/bin/ld: ../../server/shared/libshared.a(Util.cpp.o): неопределённая ссылка на символ «pthread_getspecific@@GLIBC_2.0»
//lib/i386-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [src/tools/mmaps_generator/mmaps_generator] Ошибка 1
make[1]: **\* [src/tools/mmaps_generator/CMakeFiles/mmaps_generator.dir/all] Ошибка 2
make[1]: **\* Ожидание завершения заданий...

**Comment by callmephil** [comment]
use linux branch for compiling under linux.

**Comment by Motorheadx** [comment]
this branch is the same error

**Comment by lashia** [comment]
Can u add me in skype ?

**Comment by lashia** [comment]
I will help u or use trinity core guid for me it works well

**Comment by Motorheadx** [comment]
I would add in Skype but not speak English =))

**Comment by lashia** [comment]
Lashh...a <---

**Comment by Motorheadx** [comment]
60 Reva trinitycore the cards fit well =)

**Comment by lashia** [comment]
there would be some issues i think u must use which sunwell shared

**Comment by boom8866** [comment]
@lashia  
error：
Installation appears   ACE6.0 Above version
ACE_wrappers/apps/gperf/tests/test.cpp:28
