### ISSUE TITLE
Refer a friend Summon 

### ISSUE THREAD

**Issue by talamortis** [callmephil/SunWellCore#32]
Refer a friend summon doesnt work when out of sight of the target.

**Comment by callmephil** [comment]
Well, RAF doesn't seems to apply at first if the target is not in range of his friend. however if you disable checks in "SPELL_EFFECT_SUMMON_RAF_FRIEND" (line 5776 in spell.cpp) it will fix the summon effect.
*Note you won't be able to see icon or extra info related to RAF if you are not in group or if you are too far from your friend at login. (@todo research)

**Comment by Bungi96** [comment]
Not working summon friend how to fix? Invalid target

**Comment by ahuraa** [comment]
confirm
