### ISSUE TITLE
Patch transmogrification

### ISSUE THREAD

**Issue by Devalenok** [callmephil/SunWellCore#38]
Make please patch transmogrification , is very necessary ! Thank you.

**Comment by tea91** [comment]
Local + transmogrification = I think it was done. no more need.

**Comment by callmephil** [comment]
still working on local take huge time to fix it. transmogrification i won't implement it for now no time for it.

**Comment by igorkur** [comment]
tea91, Are not you fuck !

**Comment by Devalenok** [comment]
Topic can be closed , the question is solved .
