### ISSUE TITLE
Fixed Autobroadcasts message

### ISSUE THREAD

**Issue by alexkulya** [callmephil/SunWellCore#4]
Autobroadcasts message not work.
Solution: https://github.com/alexkulya/SunWellCore/commit/da51b7a1a611e90f88140467ac5324e72a3faf8c

add records in files LoginDatabase.cpp and LoginDatabase.h
(https://github.com/alexkulya/SunWellCore/commit/f6e57b9f0bcc11a1551c35c7f43d7e0fda852441#diff-c794d9852aae3b7121e78b62d7590e05R88
https://github.com/alexkulya/SunWellCore/commit/f6e57b9f0bcc11a1551c35c7f43d7e0fda852441#diff-4fea27b464fcc20af14658c20249de51R108)

**Comment by callmephil** [comment]
i will check that out thanks.

**Comment by callmephil** [comment]
it only show the last auto broadcast of the list. i've added 3, and only the third one is popping. it need extra checks. also .reload autobroadcast seems not working too.

**Comment by callmephil** [comment]
Ok, Issue where in Database, int where not correctly loaded. i'm pushing fix in few minutes.
