### ISSUE TITLE
Eathen Power Talent

### ISSUE THREAD

**Issue by lashia** [callmephil/SunWellCore#41]
http://wotlk.openwow.com/spell=51523  x2 has 100% chance to remove snare effects with earthbind totem its bugged doesnt remove

**Comment by Motorheadx** [comment]
can make a video and it is not clear what you want to say

**Comment by lashia** [comment]
Create shaman and mage, use enhancement talent on shaman, duel with mage and use fros nova and than use earthbind totem with shaman it must remove frost nova but it doesn't

**Comment by Motorheadx** [comment]
50% chance to also remove all snare effects from you and nearby friendly targets , read carefully what the effect it gives , and what does frost Nova

**Comment by lashia** [comment]
If you take it 2 times you get 100% chance

**Comment by Motorheadx** [comment]
I read different information on this Padova and asked friends and different players and they all said that he should not remove frost Nova , frost Nova only shoot the wolf shaman in the 2nd branch

**Comment by callmephil** [comment]
why this has been closed ?
