### ISSUE TITLE
GM Ingame command

### ISSUE THREAD

**Issue by Bungi96** [callmephil/SunWellCore#50]
Not working command .gm ingame and no in command in DB

**Comment by Motorheadx** [comment]
comnand work   //{ "ingame",         SEC_PLAYER,         true,  &HandleGMListIngameCommand,        "", NULL },=   // delete and will work

**Comment by Bungi96** [comment]
//{ "ingame", SEC_PLAYER, true, &HandleGMListIngameCommand, "", NULL },= 
where find? in cpp

**Comment by Motorheadx** [comment]
/src/server/scripts/Commands/cs_gm.cpp

**Comment by Bungi96** [comment]
thank you
