### ISSUE TITLE
Server Crash after a couple of hours 

### ISSUE THREAD

**Issue by talamortis** [callmephil/SunWellCore#66]
Hi, i seem to have came with a problem after a couple of hours of the server being on it crashes i dont know if this is a problem with the core or it could be a problem with my PC which is on windows 10. it has  net framework 4.5 and open SSL installed.

This is the error code i have been getting 

E88CB03  00000000  ?invoke_i@ACE_Thread_Adapter@@EAEKXZ+93

5E88CA3E  00000000  ?invoke@ACE_Thread_Adapter@@UAEKXZ+7E

6BEBC01D  00000000  __get_tlsindex+6F

6BEBC001  00000000  __get_tlsindex+53

74FA38F4  00000000  BaseThreadInitThunk+24

76F25E13  00000000  RtlUnicodeStringToInteger+253

76F25DDE  00000000  RtlUnicodeStringToInteger+21E

any information or feedback of what could this be will be very helpful, Thanks in advance

**Comment by lashia** [comment]
i havenot tested it on windows but on linux it has 5-6 days uptime on 50 online

**Comment by cherbert** [comment]
I have the server running on Windows 10 and its been up for a week now.

**Comment by Motorheadx** [comment]
give me a link to the server lashia =)

**Comment by talamortis** [comment]
Ive tested the server and used administrator rights uptime is of 3 days now :+1: Thanks,
