### ISSUE TITLE
Players Mute

### ISSUE THREAD

**Issue by talamortis** [callmephil/SunWellCore#68]
Hi. i was wondering how to remove the 2 hour mute from players who create a new character?

**Comment by Motorheadx** [comment]
default:
        if (sender->GetTotalPlayedTime() < 2*HOUR)
            {
                SendNotification("Speaking is allowed after playing for at least 2 hours. You may use party and guild chat.");
                recvData.rfinish();
                return;
            }

< 2*HOUR) change to your values

**Comment by talamortis** [comment]
in what file could i find this? thanks

**Comment by talamortis** [comment]
never mind found it thanks again  :+1: +
