### ISSUE TITLE
Server crashes weekly 

### ISSUE THREAD

**Issue by ceresia** [callmephil/SunWellCore#70]
Server crashes at 1AM weekly on Sunday for the past 4 weeks:

Revision: SunwellCore rev.  () (Win32, Release)
Date 1:5:2016. Time 1:0 
//=====================================================
**\* Hardware ***
Processor: AMD FX-8320E Eight-Core Processor  
Number Of Processors: 8
Physical Memory: 4194303 KB (Available: 1746788 KB)
Commit Charge Limit: 4194303 KB

**\* Operation System ***
Windows 7 Professional Service Pack 1 (Version 6.1, Build 7601)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  015FDA34 01:002DCA34 C:\Sunwell\worldserver.exe

Registers:
EAX:00000204
EBX:019AF1A8
ECX:6A170D3D
EDX:152EF1DC
ESI:019AF27C
EDI:019AF290
CS:EIP:0023:015FDA34
SS:ESP:002B:086DE608  EBP:086DF618
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010212

Call stack:
Address   Frame     Function      SourceFile
015FDA34  00000000  0001:002DCA34 C:\Sunwell\worldserver.exe
015C3AF2  00000000  0001:002A2AF2 C:\Sunwell\worldserver.exe
01484E59  00000000  0001:00163E59 C:\Sunwell\worldserver.exe
014B25E2  00000000  0001:001915E2 C:\Sunwell\worldserver.exe
014B10AF  00000000  0001:001900AF C:\Sunwell\worldserver.exe
014D47B9  00000000  0001:001B37B9 C:\Sunwell\worldserver.exe
01519A4A  00000000  0001:001F8A4A C:\Sunwell\worldserver.exe
014B93EB  00000000  0001:001983EB C:\Sunwell\worldserver.exe
014B91CD  00000000  0001:001981CD C:\Sunwell\worldserver.exe
014C16A1  00000000  0001:001A06A1 C:\Sunwell\worldserver.exe
014C11E0  00000000  0001:001A01E0 C:\Sunwell\worldserver.exe
014FA8A3  00000000  0001:001D98A3 C:\Sunwell\worldserver.exe
6A09CB03  00000000  ?invoke_i@ACE_Thread_Adapter@@EAEKXZ+93
6A09CA3E  00000000  ?invoke@ACE_Thread_Adapter@@UAEKXZ+7E
6A17C01D  00000000  __get_tlsindex+6F
6A17C001  00000000  __get_tlsindex+53
764E338A  00000000  BaseThreadInitThunk+12
775E9A02  00000000  RtlInitializeExceptionChain+63
# 775E99D5  00000000  RtlInitializeExceptionChain+36

Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
015FDA34  00000000  0001:002DCA34 C:\Sunwell\worldserver.exe

015C3AF2  00000000  0001:002A2AF2 C:\Sunwell\worldserver.exe

01484E59  00000000  0001:00163E59 C:\Sunwell\worldserver.exe

014B25E2  00000000  0001:001915E2 C:\Sunwell\worldserver.exe

014B10AF  00000000  0001:001900AF C:\Sunwell\worldserver.exe

014D47B9  00000000  0001:001B37B9 C:\Sunwell\worldserver.exe

01519A4A  00000000  0001:001F8A4A C:\Sunwell\worldserver.exe

014B93EB  00000000  0001:001983EB C:\Sunwell\worldserver.exe

014B91CD  00000000  0001:001981CD C:\Sunwell\worldserver.exe

014C16A1  00000000  0001:001A06A1 C:\Sunwell\worldserver.exe

014C11E0  00000000  0001:001A01E0 C:\Sunwell\worldserver.exe

014FA8A3  00000000  0001:001D98A3 C:\Sunwell\worldserver.exe

6A09CB03  00000000  ?invoke_i@ACE_Thread_Adapter@@EAEKXZ+93

6A09CA3E  00000000  ?invoke@ACE_Thread_Adapter@@UAEKXZ+7E

6A17C01D  00000000  __get_tlsindex+6F

6A17C001  00000000  __get_tlsindex+53

764E338A  00000000  BaseThreadInitThunk+12

775E9A02  00000000  RtlInitializeExceptionChain+63

775E99D5  00000000  RtlInitializeExceptionChain+36

**Comment by Dude100** [comment]
compile in debug mode..

**Comment by Artamedes** [comment]
Delete Ace.dll and upgrade to use Boost in the core.

**Comment by FALL1N1** [comment]
(Win32, Release) noob..

also the crash is from the spline movement, not ace

**Comment by Dude100** [comment]
@JunkyBulgaria do you fix this
http://pastebin.com/XkCLs7Bd
