### ISSUE TITLE
All npcs casting triggered(instant) spells without casttime.

### ISSUE THREAD

**Issue by FALL1N1** [callmephil/SunWellCore#73]
Anyone else experienced this issue?

**Comment by callmephil** [comment]
nop.

**Comment by FALL1N1** [comment]
https://gist.github.com/JunkyBulgaria/1c2605970d75fd9d9892a9bebd7dbb4d
that fixed it (ignore the cheat command part i have implemented them on my fork but you can just delete it) probably somethings broken with checking these flags for charge, we can do it with a if() check with the spellfamily then set the cast time to 0 and after it the m_casttime = m_spellInfo->CalcCastTime();

```
// calculate cast time (calculated after first CheckCast check to prevent charge counting for first CheckCast fail)
m_casttime = (_triggeredCastFlags & TRIGGERED_CAST_DIRECTLY) ? 0 : m_spellInfo->CalcCastTime(m_caster, this);
```

to
m_casttime = m_spellInfo->CalcCastTime();

if you are running a private project i can send you the proper fix trough pm, wont do anything public because of the ungrateful retards that's arround here

**Comment by ghost** [comment]
Apparently once you met with this error. Yes, and I did not notice this problem. And who are you ungrateful name?))
