### ISSUE TITLE
黑翼之巢1号BOSS 蛋不会消失

### ISSUE THREAD

**Issue by PkllonG** [callmephil/SunWellCore#81]

**Comment by PkllonG** [comment]
go -7673    -1106    397    469

**Comment by szhxjt1334** [comment]
请用英语描述，这个端60年代修复不怎么样的。
pls describe it with english,the classic raid and dungen scripts are not fixed.

**Comment by FALL1N1** [comment]
https://gist.github.com/JunkyBulgaria/9f90cdafd9ba7eeea54ed1020f2310b9
