### ISSUE TITLE
Enchanting 

### ISSUE THREAD

**Issue by Ramys** [callmephil/SunWellCore#95]
Enchanting  Profession  with 3  [Disenchant]

**Comment by talamortis** [comment]
More detail?

**Comment by Ramys** [comment]
When you learn to enchanting profession in spellbook appears 3 Disencant

**Comment by talamortis** [comment]
You must have a different databse version, this repo is dead now 

use this repo. [https://github.com/azerothcore/azerothcore-wotlk](url)

**Comment by Ramys** [comment]
What database for this core ?
auth,characters in world?
